### ISSUE TITLE
querying the image for view error

### ISSUE THREAD

**Issue by hahadaxia** [tableau/server-client-python#438]
i download your tableau server  TableauServer-64bit-2019-2-0.exe   from  your official website. and now the server default api is 2.3.
 I want to download view image from the sample code in https://github.com/tableau/server-client-python/blob/master/samples/download_view_image.py
  , i meet the  bug tip:
400065: Bad Request
The filter query contains a key which is not recognized for this api version.
so i use the "server = TSC.Server('http://SERVER_URL', use_server_version=True)" 
and get the lastest version, the api is 3.4. but meet other bug tip:
	400074: Bad Request
        There was a problem querying the image for view 'my_view_id'.
i can login and get the view_name ,but after populate the image, write the png , the bug tip will print. how to fix this bug?

**Comment by illonage** [comment]
Hi,
Can you try to republish the workbook on your Server and try again, please?

**Comment by hahadaxia** [comment]
> Hi,
> Can you try to republish the workbook on your Server and try again, please?

thanks，i  fix the bug.

**Comment by ferraijv** [comment]
@hahadaxia I'm having this same issue. What was the fix?

**Comment by krishnasaiv** [comment]
0

I was facing a similar error & neither the documentation of Python API nor the REST API had no info about this issue. ( I couldn't even find the error code in both)

But after a long search, I stumbled upon a suggestion by the user 'gaoang2148' in this thread.

For me, the error was occuring because a few data sources in my workbook were missing connection credentials ( The credentials were missing after I published an update from Tableau Desktop). Once I embedded the credentials for each data source, the code was working fine again.

**Comment by lanphuong987** [comment]
For those who are still encountering this problem, you can find a solution here: https://help.tableau.com/current/pro/desktop/en-us/publishing_sharing_authentication.htm. I change authentication type of view to Embedded password, and my code work
